# Generated by Django 4.2.4 on 2023-12-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Shipping_address',
            new_name='address',
        ),
    ]
