# Generated by Django 4.2.4 on 2023-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_shipping_address_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/avatar.png', null=True, upload_to='profile'),
        ),
    ]
